import type { Metadata } from "next";
import Link from "next/link";
import SessionProvider from "./components/SessionProvider";
import { getServerSession } from "next-auth";
import Image from "next/image";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import { User } from "./components/User";

const spartan = League_Spartan({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en" className={`${spartan.className} dark`}>
      <body className="relative min-h-screen bg-slate-200 antialiased dark:bg-slate-900">
        <SessionProvider session={session}>
          <nav
            aria-label="Main navigation"
            className="left-0 flex h-16 w-full items-center bg-blue-950 md:h-20 lg:fixed lg:h-full lg:w-24 lg:flex-col lg:rounded-r-3xl"
          >
            <div className="ml-auto flex items-center pr-6 lg:ml-0 lg:mt-auto lg:flex-col lg:pb-6 lg:pr-0">
              <Link href="/">
                <Image
                  className="absolute left-0 top-0 h-16 w-16 md:h-20 md:w-20 lg:h-24 lg:w-24"
                  src="/logo.svg"
                  alt="company logo"
                  width={103}
                  height={103}
                />
              </Link>
              <User />
            </div>
          </nav>
          <main className="flex justify-center px-6 py-8 md:px-12 md:py-14 lg:py-16 lg:pl-24">
            <div className="w-full max-w-3xl">{children}</div>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
